baseURL = 'https://clintreyes.github.io/'
languageCode = 'en-us'
title = 'Clint C. M. Reyes'
theme = 'ananke'

[caches]
	[caches.images]
		dir = ':cacheDir/images'

[markup.goldmark.renderHooks.image]
enableDefault = true

[markup.goldmark.renderHooks.link]
enableDefault = true